### ISSUE TITLE
CRITICAL - Fatal Error: Uncaught Error: Call to undefined method appDevDebugProjectContainer::isScopeActive()

### ISSUE THREAD

**Issue by pedroresende** [avanzu/AdminThemeBundle#90]
This error occurs when adding the The Sidebar Navigation Component. After adding the service I get the following error

```
Error: Uncaught Error: Call to undefined method appDevDebugProjectContainer::isScopeActive() in /Users/pedroresende/Desktop/uniquepassword/var/cache/dev/classes.php:7368
Stack trace:
#0 /Users/pedroresende/Desktop/uniquepassword/vendor/kriswallsmith/assetic/src/Assetic/Extension/Twig/ValueContainer.php(76): Symfony\Bundle\AsseticBundle\DefaultValueSupplier->getValues()
#1 /Users/pedroresende/Desktop/uniquepassword/vendor/kriswallsmith/assetic/src/Assetic/Extension/Twig/ValueContainer.php(61): Assetic\Extension\Twig\ValueContainer->initialize()
#2 /Users/pedroresende/Desktop/uniquepassword/var/cache/dev/classes.php(4984): Assetic\Extension\Twig\ValueContainer->getIterator()
#3 /Users/pedroresende/Desktop/uniquepassword/var/cache/dev/classes.php(4989): Monolog\Formatter\NormalizerFormatter->normalize(Object(Assetic\Extension\Twig\ValueContainer))
#4 /Users/pedroresende/Desktop/uniquepassword/var/cache/dev/classes.php(4989): Monolog\Formatter\NormalizerFormatter->normalize(Array)
#5 /Users/pedroresende/Desktop/uniquepa 
``
```

**Comment by pedroresende** [comment]
The only workaround I've found is to use in the EventListener

```
use Avanzu\AdminThemeBundle\Event\SidebarMenuEvent;
use Avanzu\AdminThemeBundle\Model\MenuItemModel;
```

instead of 

```
use MyAdminBundle\Model\MenuItemModel;
use Avanzu\AdminThemeBundle\Event\SidebarMenuEvent;
```

**Comment by shakaran** [comment]
@pedroresende with new symfony versions and new version of this bundle, is it still an issue?

**Comment by shakaran** [comment]
@pedroresende if you still have the chance of test with latest master would be great to know the status of this issue, thanks!

**Comment by shakaran** [comment]
Closing as inactive bug, I cannot reproduce it in latest master. So please reopen in any moment if you are interested or reproducible again.
